name: build and deploy

on:
  push:
    branches: [ wasm ]
  pull_request:
    branches: [ wasm ]

jobs:
  # Build job
  build:
    # Specify runner +  build & upload the static files as an artifact
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        id: build
        uses: actions/checkout@main

      - name: Emcc Setting
        uses: mymindstorm/setup-emsdk@v14

      - name: Verify emcc
        run: emcc -v

      - name: Run make
        run: make
          # <Not provided for brevity>
          # At a minimum this step should build the static files of your site
          # <Not provided for brevity>

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: target

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
